# 포트 설정 및 한글 깨지는 현상 방지
server:
  port: 8085
  servlet:
    encoding:
      force-response: true

spring:
  # Swagger 적용
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # DB 적용
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Jpa 설정
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.enable_lazy_load_no_trans: true

  # 소셜 로그인 Google
  security:
    oauth2:
      client:
        registration:

          # 소셜 로그인 Naver
          naver:
            scope: name, email
            client-name: Naver
            authorization-grant-type: authorization_code
            # redirect-uri: http://localhost:8085/login/oauth2/code/naver

          # 소셜 로그인 Kakao
          kakao:
            scope: profile_nickname, profile_image, account_email, birthday
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            # redirect-uri: http://localhost:8085/login/oauth2/code/kakao

        # 소셜 로그인 Provider 설정
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # Redis 설정
  redis:
    port: 6379

# Email 인증
mail:
  smtp:
    auth: true
    port: 465
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465

# admin 구글 계정
AdminMail:
  id: ${ADMINMAIL_ID}

# multipart 설정
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

# S3 설정
cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    credentials:
      accessKey: ${CLOUD_AWS_CREDENTIALS_ACCESS-KEY}
      secretKey: ${CLOUD_AWS_CREDENTIALS_SECRET-KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    com.zaxxer.hikari.HikariConfig: TRACE
    com.zaxxer.hikari: TRACE

# 아임 포트 설정
imp_key: ${IMP_KEY}
imp_secret: ${IMP_SECRET}
