# 한글 깨지는 현상 방지
server:
  port: 8081
  servlet:
    encoding:
      force-response: true
spring:
  # Swagger 적용
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # DB 적용
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mySQL
    username: root
    password: password
  # Jpa 설정
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.enable_lazy_load_no_trans: true

  # 소셜 로그인 Google
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 769882399475-ic1aib52em6i83quog4r4s3rdni419j4.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          # 소셜 로그인 Naver
          naver:
            client-id: g9875gcNn4EkQNBmmuvZ
            client-secret: yYWJVLQz8Z
            scope: name, email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
          # 소셜 로그인 Kakao
          kakao:
            client-id: 3dee652d714c0a8597499ec61dca7af2
            client-secret: 24HCDwiEUoCBKpAhKBM8puTgN6B8LXS3
            scope: profile_nickname, profile_image, account_email, birthday
            client-name: Kakao
            authorization-grant-type: authorization_code
#            redirect-uri: http://ec2-54-180-115-200.ap-northeast-2.compute.amazonaws.com:8081/login/oauth2/code/kakao
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            client-authentication-method: POST
        # 소셜 로그인 Provider 설정 ( Naver, Kakao )
        provider:
          # Naver
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          #Kakao
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  # Redis 설정
  redis:
    host: ec2-3-39-131-153.ap-northeast-2.compute.amazonaws.com
    port: 6379
    password: password

# Email 인증
mail:
  smtp:
    auth: true
    port: 465
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465

# admin 구글 계정
AdminMail:
  id: skdlfma123@gmail.com
  password: ugwplewriwktlvss

# multipart 설정
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

# aws 설정
cloud:
  aws:
    credentials:
      accessKey: accessKey
      secretKey: secretKey
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: airplanning-bucket

logging:
  level:
    com.zaxxer.hikari.HikariConfig: TRACE
    com.zaxxer.hikari: TRACE

# 아임 포트 설정
imp_key: ${IMP_KEY}
imp_secret: ${IMP_SECRET}
